#                                                   Feature Extracting :)

we will make new columns that help answer business questions

In [9]:
import pandas as pd
import numpy as np

In [10]:
df = pd.read_csv("cleaned_supply_chain.csv",encoding='latin1')
df.head()

,Type,Days for shipping (real),Days for shipment (scheduled),Benefit per order,Sales per customer,Delivery Status,Late_delivery_risk,Category Id,Category Name,Customer City,...,Order Profit Per Order,Order Region,Order State,Order Status,Product Card Id,Product Category Id,Product Name,Product Price,shipping date (DateOrders),Shipping Mode
0,DEBIT,3,4,91.250000,314.640015,Advance shipping,0,73,Sporting Goods,Caguas,...,91.250000,Southeast Asia,Java Occidental,COMPLETE,1360,73,Smart watch,327.75,2018-02-03 22:56:00,Standard Class
1,TRANSFER,5,4,-249.089996,311.359985,Late delivery,1,73,Sporting Goods,Caguas,...,-249.089996,South Asia,RajastÃ¡n,PENDING,1360,73,Smart watch,327.75,2018-01-18 12:27:00,Standard Class
2,CASH,4,4,-247.779999,309.720001,Shipping on time,0,73,Sporting Goods,San Jose,...,-247.779999,South Asia,RajastÃ¡n,CLOSED,1360,73,Smart watch,327.75,2018-01-17 12:06:00,Standard Class
3,DEBIT,3,4,22.860001,304.809998,Advance shipping,0,73,Sporting Goods,Los Angeles,...,22.860001,Oceania,Queensland,COMPLETE,1360,73,Smart watch,327.75,2018-01-16 11:45:00,Standard Class
4,PAYMENT,2,4,134.210007,298.250000,Advance shipping,0,73,Sporting Goods,Caguas,...,134.210007,Oceania,Queensland,PENDING_PAYMENT,1360,73,Smart watch,327.75,2018-01-15 11:24:00,Standard Class

In [39]:
df[['order date (DateOrders)', 'shipping date (DateOrders)']].dtypes
#we have make them in datetime dtype

order date (DateOrders)       datetime64[ns]
shipping date (DateOrders)    datetime64[ns]
dtype: object

In [13]:
df['order date (DateOrders)'] = pd.to_datetime(
    df['order date (DateOrders)'],
    errors='coerce'
)

df['shipping date (DateOrders)'] = pd.to_datetime(
    df['shipping date (DateOrders)'],
    errors='coerce'
)

In [14]:
df[['order date (DateOrders)', 'shipping date (DateOrders)']].dtypes

order date (DateOrders)       datetime64[ns]
shipping date (DateOrders)    datetime64[ns]
dtype: object

In [15]:
df['Order Year'] = df['order date (DateOrders)'].dt.year

In [16]:
df['Order Month'] = df['order date (DateOrders)'].dt.month_name()

In [17]:
df['Order Quarter'] = df['order date (DateOrders)'].dt.quarter

In [18]:
df['Order Day'] = df['order date (DateOrders)'].dt.day_name()

In [19]:
df.head()

,Type,Days for shipping (real),Days for shipment (scheduled),Benefit per order,Sales per customer,Delivery Status,Late_delivery_risk,Category Id,Category Name,Customer City,...,Product Card Id,Product Category Id,Product Name,Product Price,shipping date (DateOrders),Shipping Mode,Order Year,Order Month,Order Quarter,Order Day
0,DEBIT,3,4,91.250000,314.640015,Advance shipping,0,73,Sporting Goods,Caguas,...,1360,73,Smart watch,327.75,2018-02-03 22:56:00,Standard Class,2018,January,1,Wednesday
1,TRANSFER,5,4,-249.089996,311.359985,Late delivery,1,73,Sporting Goods,Caguas,...,1360,73,Smart watch,327.75,2018-01-18 12:27:00,Standard Class,2018,January,1,Saturday
2,CASH,4,4,-247.779999,309.720001,Shipping on time,0,73,Sporting Goods,San Jose,...,1360,73,Smart watch,327.75,2018-01-17 12:06:00,Standard Class,2018,January,1,Saturday
3,DEBIT,3,4,22.860001,304.809998,Advance shipping,0,73,Sporting Goods,Los Angeles,...,1360,73,Smart watch,327.75,2018-01-16 11:45:00,Standard Class,2018,January,1,Saturday
4,PAYMENT,2,4,134.210007,298.250000,Advance shipping,0,73,Sporting Goods,Caguas,...,1360,73,Smart watch,327.75,2018-01-15 11:24:00,Standard Class,2018,January,1,Saturday

# checking things of shipping time

In [21]:
df['Shipping Time'] = (
    df['shipping date (DateOrders)'] -
    df['order date (DateOrders)']
).dt.days

In [23]:
df[['Shipping Time','Days for shipping (real)']].head()

   Shipping Time  Days for shipping (real)
0              3                         3
1              5                         5
2              4                         4
3              3                         3
4              2                         2

In [24]:
#everything is good

In [29]:
#shipping delay
df['Shipping Delay'] = (
    df['Days for shipping (real)'] -
    df['Days for shipment (scheduled)']
)
df['Shipping Delay'].head(5)
# <0 == earlier dilevery 
# =0 == on time dilevary
# >0 == delayed dilvery

0   -1
1    1
2    0
3   -1
4   -2
Name: Shipping Delay, dtype: int64

In [30]:
#profit margin
df['Profit Margin (%)'] = (
    df['Order Profit Per Order'] / df['Sales']
) * 100

In [31]:
df['Profit Margin (%)'].head(7)

0    27.841342
1   -75.999999
2   -75.600305
3     6.974829
4    40.948896
5     5.668955
6    29.040427
Name: Profit Margin (%), dtype: float64

In [32]:
#high value orders
df['High Value Order'] = np.where(
    df['Sales'] >= df['Sales'].median(),
    'High',
    'Low'
)
df['High Value Order'].head(7)

0    High
1    High
2    High
3    High
4    High
5    High
6    High
Name: High Value Order, dtype: object

In [34]:
#discount
df['Calculated Discount'] = (
    df['Order Item Product Price'] *
    df['Order Item Quantity'] *
    df['Order Item Discount Rate']
)
df['Calculated Discount'].head(7)

0    13.110000
1    16.387500
2    19.665000
3    22.942500
4    29.497501
5    32.775000
6    39.329999
Name: Calculated Discount, dtype: float64

In [35]:
#weekend order
df['Weekend Order'] = np.where(
    df['Order Day'].isin(['Saturday', 'Sunday']),
    'Yes',
    'No'
)

In [36]:
df['Weekend Order'].head()

0     No
1    Yes
2    Yes
3    Yes
4    Yes
Name: Weekend Order, dtype: object

# Saving the data

In [38]:
df.to_csv('Feature_extracted_data.csv', index=False)